#!/bin/sh

parseCHANGES='
if (m/^\* v[^v]*(v[0-9]+\.[0-9]+[^ ]*) +\(released/) {
    print $1;
    exit 0
}'

version='no-version-yet'

findprg() {
    _prg="$1"
    REPLY=''
    _oldifs="$IFS"
    IFS=':'
    for dir in $PATH; do
        f="$dir/$_prg"
        if [ -x "$f" ]; then
            REPLY="$f"
            IFS="$_oldifs"
            return 0
        fi
    done
    IFS="$_oldifs"
    return 1
}

if findprg git; then
    gotgit=1
    git="$REPLY"
else
    gotgit=0
fi

if [ "$gotgit" -gt 0 ]; then
    if [ "$("$git" rev-parse --is-inside-work-tree 2>/dev/null)" = 'true' ]
    then
        version="$("$git" describe --always)"
        version=${version#v}
        if test -n "$("$git" diff-index --name-only HEAD --)"; then
            version=${version}-dirty
        fi
    fi
fi

if [ "$version" = 'no-version-yet' ]; then
    # Either, there's no git installed, or we don't have git repository infor-
    # mation while trying to figure out the project's version. Fall back the to
    # the version in the latest release note in CHANGES.
    version=$(perl -ne "$parseCHANGES" < CHANGES)
fi

printf '%s\n' "$version"

if [ "$version" = 'no-version-yet' ]; then
    exit 1
fi

exit 0
